mystr = "harry is a good boy"
print(mystr[4])
print(mystr[0:5])
print(mystr[0:])
print(mystr[0:5:2])
print(mystr[::3])
print(mystr[::5559])
print(mystr[-4:-1])
print(mystr[::-2])
print(mystr.endswith("boy"))
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.capitalize())
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("boy","girl"))
print(mystr.count("o"))
print(mystr.split())
print(mystr.find("is"))

